/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_javatiku_keymanager_utils_JniEncryptUtil */

#ifndef _Included_cn_javatiku_keymanager_utils_JniEncryptUtil
#define _Included_cn_javatiku_keymanager_utils_JniEncryptUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_javatiku_keymanager_utils_JniEncryptUtil
 * Method:    decryptString
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cn_javatiku_keymanager_utils_JniEncryptUtil_decryptString
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     cn_javatiku_keymanager_utils_JniEncryptUtil
 * Method:    encryptString
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cn_javatiku_keymanager_utils_JniEncryptUtil_encryptString
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     cn_javatiku_keymanager_utils_JniEncryptUtil
 * Method:    generateUrlSign
 * Signature: ([B[B[B[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_javatiku_keymanager_utils_JniEncryptUtil_generateUrlSign
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     cn_javatiku_keymanager_utils_JniEncryptUtil
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_javatiku_keymanager_utils_JniEncryptUtil_getVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
